package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* miércoles 6 de enero de 2016 20H29' COT
*/

public interface HelloOperations 
{
  String sayHello ();

  //declaracion de la operacion
  void shutdown ();
} // interface HelloOperations

//comando para establecer todo el sistema de paquetes. idlj -fall Hello.idl